In [1]:
! pip install faker

Collecting faker
  Downloading Faker-36.1.1-py3-none-any.whl.metadata (15 kB)
Collecting tzdata (from faker)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Downloading Faker-36.1.1-py3-none-any.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/1.9 MB 4.2 MB/s eta 0:00:01
   --------------------------- ------------ 1.3/1.9 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 3.3 MB/s eta 0:00:00
Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: tzdata, faker
Successfully installed faker-36.1.1 tzdata-2025.1

In [2]:
! pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp39-cp39-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.22.4 in d:\rag_langchain\venv\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\rag_langchain\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in d:\rag_langchain\venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in d:\rag_langchain\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp39-cp39-win_amd64.whl (11.6 MB)
Using cached pytz-2025.1-py2.py3-none-any.whl (507 kB)
Installing collected packages: pytz, pandas
Successfully installed pandas-2.2.3 pytz-2025.1

In [1]:
import pandas as pd
import random
from faker import Faker

def generate_synthetic_data(n=1000):
    fake = Faker("id_ID")  
    Faker.seed(42)
    random.seed(42)
    
    data = []
    
    kategori_produk = [
        "Kesehatan", 
        "Peralatan Rumah", 
        "Elektronik", 
        "Fashion", 
        "Makanan"
        ]
    metode_pembayaran = [
        "E-Wallet", 
        "Transfer Bank", 
        "Kartu Kredit", 
        "Kartu Debit", 
        "Virtual Account", 
        "QRIS", 
        "Cash on Delivery (COD)", 
        "Kredivo",
        "Dana" 
        ]

    alamat_dict = {}
    harga_produk_dict = {}
    
    for i in range(1, n+1):
        id_transaksi = f"T{i:05d}"
        id_pengguna = f"U{random.randint(1000, 9999)}"
        id_produk = f"P{random.randint(100, 999)}"
        waktu_transaksi = fake.date_between(start_date="-1y", end_date="today").strftime("%Y-%m-%d")
        jumlah_transaksi = random.randint(1, 10)
        metode_pembayaran_terpilih = random.choice(metode_pembayaran)
        
        if id_pengguna in alamat_dict:
            alamat_pengiriman = alamat_dict[id_pengguna]
        else:
            alamat_pengiriman = fake.address().replace("\n", ", ")
            alamat_dict[id_pengguna] = alamat_pengiriman
        
        kategori_produk_terpilih = random.choice(kategori_produk)
        penilaian_produk = random.randint(1, 5)
        
        if id_produk in harga_produk_dict:
            harga_satuan = harga_produk_dict[id_produk]
        else:
            harga_satuan = random.randint(50000, 5000000)
            harga_produk_dict[id_produk] = harga_satuan
        
        total_harga = harga_satuan * jumlah_transaksi
        
        data.append([
            id_transaksi, id_pengguna, id_produk, waktu_transaksi, jumlah_transaksi,
            metode_pembayaran_terpilih, alamat_pengiriman, kategori_produk_terpilih,
            penilaian_produk, total_harga
        ])
    
    df = pd.DataFrame(data, columns=[
        "ID_Transaksi", "ID_Pengguna", "ID_Produk", 
        "Waktu_Transaksi", "Jumlah_Transaksi",
        "Metode_Pembayaran", "Alamat_Pengiriman", 
        "Kategori_Produk", "Penilaian_Produk", "Total_Harga"
    ])
    
    return df

In [2]:
df_sintetis = generate_synthetic_data(n=1000)
df_sintetis.to_csv("synthetic_transaction_data.csv", index=False)
print(df_sintetis.head())

  ID_Transaksi ID_Pengguna ID_Produk Waktu_Transaksi  Jumlah_Transaksi  \
0       T00001       U2824      P125      2024-10-21                 5
1       T00002       U9935      P189      2024-09-20                10
2       T00003       U4582      P338      2024-03-24                 9
3       T00004       U7873      P325      2024-12-12                 8
4       T00005       U6574      P384      2024-11-25                 3

        Metode_Pembayaran                                  Alamat_Pengiriman  \
0             Kartu Debit         Jalan Merdeka No. 181, Bandung, Bali 33890
1  Cash on Delivery (COD)   Gg. Kutai No. 02, Makassar, Kepulauan Riau 35116
2                E-Wallet            Jalan Erlangga No. 1, Bau-Bau, LA 93103
3         Virtual Account               Jl. Sukabumi No. 75, Medan, NT 41928
4             Kartu Debit  Gang Pasteur No. 8, Tangerang Selatan, Maluku ...

   Kategori_Produk  Penilaian_Produk  Total_Harga
0  Peralatan Rumah                 2      4548955
1        Kesehatan                 1      8359720
2          Makanan                 2     41591700
3        Kesehatan                 2     28761168
4       Elektronik                 1      2484024

In [3]:
df_sintetis

,ID_Transaksi,ID_Pengguna,ID_Produk,Waktu_Transaksi,Jumlah_Transaksi,Metode_Pembayaran,Alamat_Pengiriman,Kategori_Produk,Penilaian_Produk,Total_Harga
0,T00001,U2824,P125,2024-10-21,5,Kartu Debit,"Jalan Merdeka No. 181, Bandung, Bali 33890",Peralatan Rumah,2,4548955
1,T00002,U9935,P189,2024-09-20,10,Cash on Delivery (COD),"Gg. Kutai No. 02, Makassar, Kepulauan Riau 35116",Kesehatan,1,8359720
2,T00003,U4582,P338,2024-03-24,9,E-Wallet,"Jalan Erlangga No. 1, Bau-Bau, LA 93103",Makanan,2,41591700
3,T00004,U7873,P325,2024-12-12,8,Virtual Account,"Jl. Sukabumi No. 75, Medan, NT 41928",Kesehatan,2,28761168
4,T00005,U6574,P384,2024-11-25,3,Kartu Debit,"Gang Pasteur No. 8, Tangerang Selatan, Maluku ...",Elektronik,1,2484024
...,...,...,...,...,...,...,...,...,...,...
995,T00996,U7813,P980,2024-11-09,8,Cash on Delivery (COD),"Gang Asia Afrika No. 913, Kota Administrasi Ja...",Makanan,2,30893888
996,T00997,U9346,P534,2024-06-22,9,Kredivo,"Gg. Kebonjati No. 146, Tanjungpinang, KR 69995",Fashion,3,35226036
997,T00998,U4698,P290,2024-03-24,7,E-Wallet,"Jl. Raya Ujungberung No. 557, Prabumulih, NB 3...",Makanan,4,10148383
998,T00999,U4878,P829,2024-03-27,9,Virtual Account,"Jalan Laswi No. 68, Bima, Sulawesi Tengah 33351",Fashion,5,35103186
999,T01000,U7012,P134,2024-03-01,1,Kredivo,"Jalan Pelajar Pejuang No. 9, Gorontalo, JK 39114",Elektronik,1,4917647